# Generated by Django 5.1.6 on 2025-02-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list_app', '0004_alter_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.TextField(default=True, null=True),
        ),
    ]
