# Generated by Django 5.1.6 on 2025-02-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list_app', '0005_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
